# Generated by Django 5.0.4 on 2024-04-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
