# Generated by Django 5.0.4 on 2024-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_dues_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='loan_id',
            field=models.IntegerField(),
        ),
    ]
