# Generated by Django 5.0.4 on 2024-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
