# Generated by Django 5.0.4 on 2024-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aadhar_id', models.CharField(max_length=12, unique=True)),
                ('credit_score', models.IntegerField(default=0)),
            ],
        ),
    ]
